version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:password123@database:5432/fastfood
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastfood
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

volumes:
  postgres_data: