apiVersion: v1
kind: Service
metadata:
  name: postgres-service-internal
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-external
spec:
  selector:
    app: postgres
  ports:
  - port: 5454
    targetPort: 5432
    nodePort: 30432
    protocol: TCP
  type: NodePort