apiVersion: v1
kind: Service
metadata:
  name: fastfood-app-service
spec:
  type: NodePort
  selector:
    app: fastfood-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP