apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: migration
        image: henriquemh/fastfood-app:latest
        command: 
        - /bin/sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          sleep 10
          bun run migrate
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database_url
      restartPolicy: OnFailure

