apiVersion: batch/v1
kind: Job
metadata:
  name: seed-job
spec:
  template:
    spec:
      containers:
      - name: seed
        image: henriquemh/fastfood-app:latest
        command: 
        - /bin/sh
        - -c
        - |
          bun run generate
          bun run seed
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: database_url
      restartPolicy: OnFailure
