apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
data:
  POSTGRES_USER: "admin"
  POSTGRES_DB: "fastfood"
  DATABASE_URL: postgresql://admin:${DATABASE_PASSWORD}@postgres-service-internal:5432/fastfood