apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  database_password: cGFzc3dvcmQxMjM=
  database_url: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkMTIzQHBvc3RncmVzLXNlcnZpY2UtaW50ZXJuYWw6NTQzMi9mYXN0Zm9vZA==
